language: cpp

compiler:
 - clang

addons:
  postgresql: "9.3"

before_install:
 # c++11 support
 - if [[ $(uname -s) == 'Linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo apt-get update -y;sudo apt-get install -y libstdc++6 libstdc++-4.8-dev; fi;

install:
 - createdb template_postgis
 - psql -c "CREATE EXTENSION postgis" template_postgis

before_script:
 - cd ..
 - git init .
 - git remote add origin http://github.com/mapnik/mapnik
 - git fetch
 - git checkout master
 - cd mapnik-gyp

script:
 - . build.sh