language: generic

sudo: false

addons:
  postgresql: "9.4"
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

cache:
  directories:
  - $HOME/.ccache

matrix:
  include:
    - os: linux
      compiler: clang35-release
      env: CONFIGURATION=Release CXX="ccache clang++-3.5 -Qunused-arguments"
    - os: linux
      compiler: clang35-debug
      env: CONFIGURATION=Debug CXX="ccache clang++-3.5 -Qunused-arguments"
    - os: osx
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode7.3 # upgrades clang from 6 -> 7
      compiler: clang
      env: CONFIGURATION=Release
    - os: osx
      # https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode7.3 # upgrades clang from 6 -> 7
      compiler: clang
      env: CONFIGURATION=Debug

install:
 # TODO - get postgis working
 - cd ..
 - git init .
 - git remote add origin http://github.com/mapnik/mapnik
 - git fetch
 - git checkout master
 - git submodule update --init
 - cd mapnik-gyp

script:
 - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
 - if [[ ${COMMIT_MESSAGE} =~ "[build]" ]]; then ./build.sh; fi;
 - if [[ ${COMMIT_MESSAGE} =~ "[build]" ]]; then ./test.sh; fi;
