language: cpp

os:
  - linux
  - osx

sudo: false

compiler:
 - clang

env:
  matrix:
   - CONFIGURATION=Release
   - CONFIGURATION=Debug

addons:
  postgresql: "9.4"
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-precise-3.5
    packages:
     - clang-3.5

cache:
  directories:
  - $HOME/.ccache

before_install:
 - if [[ $(uname -s) == 'Linux' ]]; then
     export CXX="ccache clang++-3.5 -Qunused-arguments";
     export CC="ccache clang-3.5 -Qunused-arguments";
   fi

install:
 # TODO - get postgis working
 - true

before_script:
 - cd ..
 - git init .
 - git remote add origin http://github.com/mapnik/mapnik
 - git fetch
 - git checkout master
 - cd mapnik-gyp

script:
 - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
 - if [[ ${COMMIT_MESSAGE} =~ "[build]" ]]; then ./build.sh; fi;
 - if [[ ${COMMIT_MESSAGE} =~ "[build]" ]]; then ./test.sh; fi;
