language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
   - CONFIGURATION=Release
   - CONFIGURATION=Debug

addons:
  postgresql: "9.3"

before_install:
 # c++11 support
 - if [[ $(uname -s) == 'Linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;sudo apt-get update -y;sudo apt-get install -y libstdc++6 libstdc++-4.8-dev; fi;
 - if [[ $(uname -s) == 'Linux' ]] && [[ "${CXX}" == 'g++' ]]; then sudo apt-get install gcc-4.8 g++-4.8; export CXX="$(which g++-4.8)"; export CC="$(which gcc-4.8)"; fi;

install:
 - sudo apt-get purge -qq -y libtiff* libjpeg* libpng3
 - sudo apt-get autoremove -y -qq
 # depends on image libraries...
 #- createdb template_postgis
 #- psql -c "CREATE EXTENSION postgis" template_postgis

before_script:
 - cd ..
 - git init .
 - git remote add origin http://github.com/mapnik/mapnik
 - git fetch
 - git checkout master
 - cd mapnik-gyp

script:
 - . build.sh
 #- ./test.sh